name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🔥 Breaking changes
    label: breaking-change
  - title: ✨ Features
    label: feature
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📚 Documentation
    label: docs
  - title: 🚫 Deprecated
    label: deprecated
  - title: 🔧 Other changes
  - title: 📦 Dependency Updates
    label: chore
    collapse-after: 5
exclude-labels:
  - skip-changelog
version-resolver:
  major:
    labels:
      - breaking-change
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
      - deprecated
      - docs
      - chore
  default: patch
autolabeler:
  - label: chore
    title:
      - /chore/i
  - label: bug
    title:
      - /bug/i
      - /fix/i
      - /bugfix/i
  - label: feature
    title:
      - /feat/i
      - /feature/i
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
template: |
  ## What's changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
